### ISSUE TITLE
Design Trust Engine

### ISSUE THREAD

**Issue by ScarTheOneTrueKing** [WWUZeroTrust/ZTN#3]
Deliverable's upon completion:
-Design the layout of the Trust Engine
-Design the network between ELK/PolicyEngine/TrustEngine

**Comment by ScarTheOneTrueKing** [comment]
From Discussion on Feb 11,

- Grab info from OSQuery (with listening connection in json format)

- Grab historical data from mysql (in order to calculate the score)

- Send its score to Policy Engine

**Comment by jstuif** [comment]
The engine will be written in Python
