### ISSUE TITLE
fleet + osquery Integration

### ISSUE THREAD

**Issue by jstuif** [WWUZeroTrust/ZTN#7]
Need to know what resources will be used for fleet. Will it sit on a Linux or Windows?

It needs to communicate with ELK.

**Comment by ProfDucksworth** [comment]
These are the plans:
Following this guide to ready osquery + ELK + Fleet for automation, host configuration, and data aggregation
https://jordanpotti.com/2018/02/16/elk-osquery-kolide-fleet-love/

Installing HELK for the ELKs stack per the instructions above
https://github.com/Cyb3rWard0g/HELK

Using Ubuntu-101 machine on Proxmox as the ELK and fleet server

**Comment by jstuif** [comment]
These are the plans:
Following this guide to ready osquery + ELK + Fleet for automation, host configuration, and data aggregation
https://jordanpotti.com/2018/02/16/elk-osquery-kolide-fleet-love/

Installing HELK for the ELKs stack per the instructions above
https://github.com/Cyb3rWard0g/HELK

Using Ubuntu-101 machine on Proxmox as the ELK and fleet server

**Comment by jstuif** [comment]
We are not running HELK stack, nor ELK until we get a proper flow of information between the user machines and the trust engine. 
Currently there are two machines for testing purpose. The Server will contains Kolide Fleet for managing queries and data gathering from the user machine, Redis for handling the data that will be storing in a MySQL server. The client machine has osquery installed and we are in the process of enabling the it to send query data to Fleet.

**Comment by jstuif** [comment]
Fleet and osquery clients are up and working. Both the server and client are sitting on Ubuntu 18.04 VMs.

**Comment by jstuif** [comment]
flag file on Fleet server:
--enroll_secret_path=/etc/osquery/enroll_secret
--tls_server_certs=/etc/osquery/localhost_8080.pem
--tls_hostname=<host_ip>
--host_identifier=hostname
--enroll_tls_endpoint=/api/v1/osquery/enroll
--config_plugin=tls
--config_tls_endpoint=/api/v1/osquery/config
--config_refresh=10
--disable_distributed=false
--distributed_plugin=tls
--distributed_interval=3
--distributed_tls_max_attempts=3
--distributed_tls_read_endpoint=/api/v1/osquery/distributed/read
--distributed_tls_write_endpoint=/api/v1/osquery/distributed/write
--logger_plugin=tls
--logger_tls_endpoint=/api/v1/osquery/log
--logger_tls_period=10
